version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: gunicorn kpro_web.wsgi:application --keyfile nginx/selftest-cert.key --certfile nginx/selftest-cert.crt --bind 0.0.0.0:8000
    expose:
      - 8000
    volumes:
      - kpro_data:/var/lib/kpro/data/
      - static_volume:/home/kpro_web/web/staticfiles
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
  nginx:
    build: ./nginx
    ports:
      - 80:80
      - 443:443
    depends_on:
      - web
    volumes:
      - static_volume:/home/kpro_web/web/staticfiles
      - kpro_data:/var/lib/kpro/data/

volumes:
  postgres_data:
  kpro_data:
  static_volume: