version: '3.8'

services:
  web:
    build: .
    container_name: kpro_web
    command: python /kpro_web/manage.py runserver_plus --key-file selftest-key --cert-file selftest-cert 0.0.0.0:8000
    volumes:
      - .:/kpro_web
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres:16
    container_name: kpro_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=kpro_web_dev
    ports:
      - 5432:5432

volumes:
  postgres_data: