# Generated by Django 4.2.3 on 2023-07-27 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceVerify',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=32, unique=True)),
                ('public_key', models.CharField(max_length=65, unique=True)),
                ('verification_start_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('success_counter', models.IntegerField(default=0)),
            ],
        ),
    ]
