# Generated by Django 4.2.3 on 2023-07-28 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device_verifier', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DeviceVerify',
            new_name='Device',
        ),
    ]
