# Generated by Django 4.2.3 on 2023-08-25 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_verifier', '0002_rename_deviceverify_device'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='public_key',
            field=models.CharField(max_length=130),
        ),
    ]
