# Generated by Django 4.2.3 on 2023-07-12 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DB_Pack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erc20.json', models.FileField(upload_to='uploads/%Y%m%d')),
                ('chain.json', models.FileField(upload_to='uploads/%Y%m%d')),
                ('pub_date', models.DateTimeField(verbose_name='upload date')),
            ],
        ),
    ]
