# Generated by Django 4.2.3 on 2023-07-12 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_updater', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DB_Pack',
            new_name='Update_Pack',
        ),
    ]
