# Generated by Django 4.2.3 on 2023-07-17 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_updater', '0004_rename_update_pack_updatepack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updatepack',
            name='chain_url',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='updatepack',
            name='erc20_url',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='updatepack',
            name='version',
            field=models.CharField(max_length=8),
        ),
    ]
