# Generated by Django 4.2.3 on 2023-07-17 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_updater', '0005_alter_updatepack_chain_url_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UpdatePack',
            new_name='UpdateDB',
        ),
    ]
