# Generated by Django 4.2.3 on 2023-07-25 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_updater', '0006_rename_updatepack_updatedb'),
    ]

    operations = [
        migrations.AddField(
            model_name='updatedb',
            name='db_hash',
            field=models.CharField(blank=True, default=None, max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='updatedb',
            name='version',
            field=models.CharField(default='202307251741', max_length=12),
        ),
    ]
